name: Model Update Trigger

on:
  push:
    paths:
      - 'models/**'  # Trigger when files in the models/ directory are updated
      - 'src/mlops_project/models.py'  # Trigger when model.py changes
      - '.github/workflows/model_update.yaml'  # Monitor updates to this workflow

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install -U pip setuptools wheel
          pip install -r requirements.txt

      - name: Retrain model
        run: |
          python src/mlops_project/models.py train --lr 0.001 --batch_size 32 --epochs 5

      - name: Upload new model
        uses: actions/upload-artifact@v3
        with:
          name: trained-model
          path: models/model.pth
